/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Kupac;
import domen.Kupovina;
import domen.Mesto;
import domen.OpstiDomenskiObjekat;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author gaga__m
 */
public class NoviKupac extends javax.swing.JFrame {

    private Kupac kupac;
    
    /**
     * Creates new form NoviKupac
     */
    public NoviKupac() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 204, 102));
        btnIzmeni.setEnabled(false);
        popuniCBMesto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaticniBr = new javax.swing.JTextField();
        txtZiroRacun = new javax.swing.JTextField();
        cmbMesto = new javax.swing.JComboBox();
        txtAdresa = new javax.swing.JTextField();
        btnSacuvajKupca = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos kupca");

        jLabel1.setText("Ime i prezime:");

        jLabel2.setText("Email:");

        jLabel3.setText("Matični broj:");

        jLabel4.setText("Žiro račun:");

        jLabel5.setText("Adresa:");

        jLabel6.setText("Mesto:");

        cmbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSacuvajKupca.setText("Sacuvaj kupca");
        btnSacuvajKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajKupcaActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacuvajKupca))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImePrezime)
                            .addComponent(txtEmail)
                            .addComponent(txtMaticniBr)
                            .addComponent(txtZiroRacun)
                            .addComponent(cmbMesto, 0, 250, Short.MAX_VALUE)
                            .addComponent(txtAdresa))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaticniBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtZiroRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajKupca)
                    .addComponent(btnZatvori)
                    .addComponent(btnIzmeni))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajKupcaActionPerformed
        String imePrezime = txtImePrezime.getText();
        String email = txtEmail.getText();
        String adresa = txtAdresa.getText();
        String maticniBr = txtMaticniBr.getText();
        String ziroRacun = txtZiroRacun.getText();
        Mesto m = (Mesto) cmbMesto.getSelectedItem();

        if (imePrezime.isEmpty() || email.isEmpty() || adresa.isEmpty() || maticniBr.isEmpty() || ziroRacun.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite sve podatke");
            return;
        } else {
            if(!email.contains("@")){
                JOptionPane.showMessageDialog(this, "Email nije dobar.");
                return;
            }
            
            Kupac k = new Kupac(-1, imePrezime, email, maticniBr, ziroRacun, adresa, m);
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.SACUVAJ_KUPCA);
            kz.setParametar(k);

            try {
                KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
                ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();

                if (so.getIzuzetak() == null) {
                    JOptionPane.showMessageDialog(this, "Sistem je zapamtio kupca");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti kupca");
                    throw new Exception(so.getIzuzetak());
                }

            } catch (IOException ex) {
                Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnSacuvajKupcaActionPerformed

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        String imePrezime = txtImePrezime.getText();
        String email = txtEmail.getText();
        String adresa = txtAdresa.getText();
        String maticniBr = txtMaticniBr.getText();
        String ziroRacun = txtZiroRacun.getText();
        Mesto m = (Mesto) cmbMesto.getSelectedItem();

        if (imePrezime.isEmpty() || email.isEmpty() || adresa.isEmpty() || maticniBr.isEmpty() || ziroRacun.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite sve podatke");
            return;
        } else {
            Kupac k = new Kupac(kupac.getKupacID(), imePrezime, email, maticniBr, ziroRacun, adresa, m);
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.IZMENI_KUPCA);
            kz.setParametar(k);

            try {
                KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
                ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();

                if (so.getIzuzetak() == null) {
                    JOptionPane.showMessageDialog(this, "Sistem je izmenio kupca");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni kupca");
                    throw new Exception(so.getIzuzetak());    
                }

            } catch (IOException ex) {
                Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoviKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoviKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoviKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoviKupac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoviKupac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSacuvajKupca;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtMaticniBr;
    private javax.swing.JTextField txtZiroRacun;
    // End of variables declaration//GEN-END:variables

    private void popuniCBMesto() {

        try {
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.VRATI_MESTA);

            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);

            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();

            List<OpstiDomenskiObjekat> lista = (List<OpstiDomenskiObjekat>) so.getOdgovor();

            cmbMesto.removeAllItems();

            for (OpstiDomenskiObjekat odo : lista) {
                Mesto m = (Mesto) odo;
                cmbMesto.addItem(m);
            }
        } catch (IOException ex) {
            Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NoviKupac.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public Kupac getKupac() {
        return kupac;
    }

    public void setKupac(Kupac kupac) {
        this.kupac = kupac;
        txtImePrezime.setText(kupac.getImePrezime());
        txtAdresa.setText(kupac.getAdresa());
        txtEmail.setText(kupac.getEmail());
        txtMaticniBr.setText(kupac.getMaticniBroj());
        txtZiroRacun.setText(kupac.getZiroRacun());
        cmbMesto.setSelectedItem(kupac.getMesto());
        this.setTitle("Izmena kupca");
        btnSacuvajKupca.setEnabled(false);
        btnIzmeni.setEnabled(true);
       

    }
}
