/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Kupovina;
import domen.OpstiDomenskiObjekat;
import domen.StavkaKupovine;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import model.ModelTabeleKupovine;
import niti.OsvezavanjeNit;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author gaga__m
 */
public class PretragaKupovina extends javax.swing.JFrame {

    /**
     * Creates new form PretragaKupovina
     */
    public PretragaKupovina() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 204, 102));
        //srediTabelu();
        OsvezavanjeNit on = new OsvezavanjeNit(this);
        on.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkKriterijum = new javax.swing.JCheckBox();
        txtKriterijumPretrage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaKupovine = new javax.swing.JTable();
        btnPrikaziDetalje = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pretraga kupovina");

        checkKriterijum.setText("Krierijum pretrage");

        tabelaKupovine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaKupovine);

        btnPrikaziDetalje.setText("Prikazi detalje / Izmeni");
        btnPrikaziDetalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljeActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(checkKriterijum)
                        .addGap(18, 18, 18)
                        .addComponent(txtKriterijumPretrage))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnPrikaziDetalje, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkKriterijum))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikaziDetalje)
                    .addComponent(btnZatvori))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziDetaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljeActionPerformed

        int red = tabelaKupovine.getSelectedRow();
        if (red != -1) {
            ModelTabeleKupovine mtk = (ModelTabeleKupovine) tabelaKupovine.getModel();
            Kupovina k = mtk.vratiMiIzabranuKupovinu(red);
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.VRATI_STAVKE);
            kz.setParametar(k);
            try {
                KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
                ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
                List<OpstiDomenskiObjekat> listaS = (List<OpstiDomenskiObjekat>) so.getOdgovor();
                List<StavkaKupovine> listaSK = new ArrayList<>();
                for (OpstiDomenskiObjekat odo : listaS) {
                    StavkaKupovine sk = (StavkaKupovine) odo;
                    listaSK.add(sk);
                }
                k.setListaStavki(listaSK);

            } catch (IOException ex) {
                Logger.getLogger(PretragaKupovina.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PretragaKupovina.class.getName()).log(Level.SEVERE, null, ex);
            }
            NovaKupovina nova = new NovaKupovina();
            nova.setKupovina(k);
        
            nova.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Nije odabrana kupovina");
        }
    }//GEN-LAST:event_btnPrikaziDetaljeActionPerformed

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaKupovina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaKupovina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaKupovina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaKupovina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaKupovina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrikaziDetalje;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JCheckBox checkKriterijum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaKupovine;
    private javax.swing.JTextField txtKriterijumPretrage;
    // End of variables declaration//GEN-END:variables

    public void srediTabelu() {
        try {

            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.VRATI_KUPOVINE);

            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();

            List<OpstiDomenskiObjekat> listaKupovinaBaza = (List<OpstiDomenskiObjekat>) so.getOdgovor();

            List<Kupovina> listaFiltriranihKupovina = new ArrayList<>();

            if (checkKriterijum.isSelected()) {
                String kriterijum = txtKriterijumPretrage.getText().trim();

                for (OpstiDomenskiObjekat o : listaKupovinaBaza) {
                    Kupovina k = (Kupovina) o;
                    Date dat = k.getDatum();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                    if (String.valueOf(k.getKupovinaID()).contains(kriterijum) || k.getKupac().getImePrezime().toLowerCase().contains(kriterijum.toLowerCase()) || k.getNapomena().toLowerCase().contains(kriterijum.toLowerCase()) || String.valueOf(k.getUkupno()).contains(kriterijum) || sdf.format(dat).contains(kriterijum.toLowerCase())) {
                        listaFiltriranihKupovina.add(k);
                    }
                }
                if (listaFiltriranihKupovina.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje kupovine po zadatoj vrednosti.");
                   
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem je nasao kupovine po zadatoj vrednosti.");
                    
                }
            } else {
                for (OpstiDomenskiObjekat o : listaKupovinaBaza) {
                    Kupovina k = (Kupovina) o;
                    listaFiltriranihKupovina.add(k);
                }
            }

            ModelTabeleKupovine mtk = new ModelTabeleKupovine(listaFiltriranihKupovina);
            tabelaKupovine.setModel(mtk);

        } catch (IOException ex) {
            Logger.getLogger(PretragaKupaca.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretragaKupaca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
